name: abc
description: description

branding:
  icon: activity
  color: gray-dark

inputs:
  token-checkout:
    description: Personal access token (PAT) used to fetch the repository
    default: ${{github.token}}
  token-uv:
    description: Personal access token (PAT) used to download uv
    default: ${{github.token}}
  flag:
    description: Example flag
    default: false

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        token: ${{inputs.token-checkout}}

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7
      with:
        github-token: ${{inputs.token-uv}}

    - name: Install 'dycw-actions'
      run: uv tool install --reinstall dycw-actions
      shell: bash

    - name: Run 'action abc'
      env:
        TOKEN: ${{inputs.token}}
        FLAG: ${{inputs.flag}}
      run: uv tool run --from dycw-actions --isolated action abc
      shell: bash
